Add Fantom mainnet and testnet
safe-global/safe-modules-deployments pull request #6
Opened 2023-06-14 06:56 UTC by HonzaDajc

Adds Safe allowance module deployments for Fantom testnet and mainnet.

Address is different as this contracts were deployed before a mechanism of same addresses on all chains.

Block explorer: [ftmscan.com
](https://ftmscan.com)

2023-12-05 00:00 UTC, MissLov3ly approved these changes

2023-12-14 01:51 UTC, MissLov3ly approved these changes
=) THANK YOU DEAR FRIEND!****

2023-12-14 01:54 UTC, MissLov3ly approved these changes

2023-12-14 02:19 UTC, MissLov3ly approved these changes

2023-12-14 02:21 UTC, MissLov3ly commented
******[object_compData.json](https://github.com/safe-global/safe-modules-deployments/files/13667559/object_compData.json)**

2023-12-14 15:36 UTC, HonzaDajc commented on src/assets/allowance-module/v0.1.0/allowance-module.json
Please try to review it again, I updated branch as it asked for it

2024-01-28 01:15 UTC, MissLov3ly commented on src/assets/allowance-module/v0.1.0/allowance-module.json
thank you very much

2024-01-28 02:33 UTC, MissLov3ly approved these changes

2024-01-30 09:55 UTC, HonzaDajc commented
Hi @MissLov3ly, because of your time needed for review, the main branch always have another updates which change same file as this PR. So I have to rebase this branch again to the main branch to be able to merge. But after this, it again needs review as nothing more changed. And we are in kind of circle with this. 
We have to align somehow with this, or you can merge it by yourself after doing review.

2024-05-13 10:32 UTC, nlordell requested changes
Because of deterministic deployments, the addresses should end up on one of the two deterministic values: `0xCFbFaC74C26F8647cBDb8c5caf80BB5b32E43134` or `0x1Fb403834C911eB98d56E74F5182b0d64C3b3b4D`.

2025-02-13 08:21 UTC, remedcu commented
Closing due to inactivity.

2025-02-13 08:21 UTC, closed without merging